[project]
channels = ["conda-forge"]
description = "Add a short description here"
name = "repos"
platforms = ["win-64"]
version = "0.1.0"

[tasks]

[dependencies]
python = "3.11.*"
scikit-learn = ">=1.5.2,<2"
pandas = ">=2.2.3,<3"
numpy = ">=2.1.2,<3"
